name: spectra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  slide_to_act: ^2.0.1
  http: ^0.13.6
  qr_flutter: ^4.1.0
  fl_chart: ^0.68.0
  geolocator: ^10.1.0

  mobile_scanner: ^3.5.6   # ✅ ADD THIS
  image_picker: ^1.0.7     # ✅ ADD THIS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poly
      fonts:
        - asset: assets/fonts/Poly-Italic.ttf